### PR TITLE
Upgrade Traefik from 2 to 3

### PR DESCRIPTION
**Pull request by matthieuwerner**

### CODE REVIEW

**Review by pyrech — APPROVED** [review]
Thanks. Could you add a note in the changelog?

**Comment by matthieuwerner** [comment]
Done

**Comment by lyrixx** [comment]
Did you check the README.md ? there are occurrence of `Host()`. It looks good to me, but it's better if you can confirm.

Otherwise, 👍🏼 and thanks

**Comment by lyrixx** [comment]
I checked, it's okay. Thanks

**Pull request merged**
