### PR TITLE
Use the new castor `open` function

### PR DESCRIPTION
**Pull request by JorickPepin**
Cf. https://github.com/jolicode/castor/pull/310

### CODE REVIEW

**Comment by lyrixx** [comment]
you need to bump the required version (\guard_min_version()`)

**Review by pyrech — APPROVED** [review]
Awesome, thanks.

Could you also update the version in the min_guard_version call from the main castor.php?

**Comment by JorickPepin** [comment]
There is no `guard_min_version` in `castor.php`, do I add one or do I add it directly in the task?

**Comment by lyrixx** [comment]
Add global one

**Review by lyrixx — APPROVED** [review]
Thanks

**Pull request merged**
