### PR TITLE
Remove docker layer caching on Github Action

### PR DESCRIPTION
**Pull request by lyrixx**

### CODE REVIEW

**Comment by lyrixx** [comment]
I'm not sure this cache layer works well. This build took
* cache restore: 0 sec
* docker build: 1m 50 sec
* cache store: 0 sec

Where other build took
* cache restore: ~30 sec
* docker build: ~ 1m 40 sec
* cache store: ~45 sec

So basically, we saved about 1 minutes by **not** using a cache ! 

image


I propose to merge #139 first, make another round of test, and if it's not better, let's drop that cache (less code == less bug)

**Comment by pyrech** [comment]
Yeah the Docker cache was a bit slow when I introduced it but it was still useful.

I have the feeling that after some time - when the cache become bigger and bigger - the restore step largely exceed build time from scratch.

An alternative of removing it entirely could be to reset it regularly (to not lose time by restoring old Docker images that are no longer used) but I'm not sure that is possible easily.

But yeah let see how it behaves with your recent changes 👍

**Comment by pyrech** [comment]
Oh I didn't see your latest comment.
That is really strange and that was not the case at the time :confused:

**Comment by lyrixx** [comment]
I confirm the cache does not work as expected. I remove it.

**Pull request merged**
