### PR TITLE
feat: add fab ps

### PR DESCRIPTION
**Pull request by jbdelhommeau**
I add `fab ps` command.

I hesitated between using native docker with filter and format or docker-composer with ps parameters.

I preferred used native docker.

 #25

### CODE REVIEW

**Comment by lyrixx** [comment]
> I preferred used native docker.

Why ?

**Comment by jbdelhommeau** [comment]
The simplest solution is just return result of docker-compose ps. But does that meet the expectations ?

@pyrech I try with fresh install. Have you specify app name or prefix ?

**Comment by lyrixx** [comment]
It looks like you messed up this git history. 
Are are using the `master` branch for both PR. 
It will be better if you use 2 separate branchs
Thanks

**Comment by jbdelhommeau** [comment]
Sorry. Bad manipulation. Done !

**Comment by lyrixx** [comment]
Thanks :+1:

**Pull request merged**
