### PR TITLE
Use latest composer build

### PR DESCRIPTION
**Pull request by hhamon**

### CODE REVIEW

**Comment by lyrixx** [comment]
Hello @hhamon. Thanks for your first contribution.

Unfortunately, we prefer to [select to specific version](https://github.com/jolicode/docker-starter/pull/59). 

So I'm not able to merge this pr in state. Could be update it to put explicitly the last version?

Thanks

**Comment by hhamon** [comment]
HI @lyrixx,

Sure, I'm updating the PR ;)

**Comment by hhamon** [comment]
@lyrixx done!

**Comment by lyrixx** [comment]
Thanks

**Pull request merged**
